# Generated by Django 3.1 on 2020-11-06 06:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('aravalli', '0003_create_shop_describe'),
    ]

    operations = [
        migrations.AddField(
            model_name='create_shop',
            name='website',
            field=models.CharField(default=django.utils.timezone.now, max_length=64),
            preserve_default=False,
        ),
    ]
