# Generated by Django 3.1 on 2020-11-06 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('aravalli', '0004_create_shop_website'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Enter the image title', max_length=100)),
                ('image', models.ImageField(upload_to='images/')),
                ('price', models.CharField(max_length=64)),
                ('products', models.TextField()),
                ('pieces', models.IntegerField()),
                ('offer', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=64)),
                ('shopname', models.CharField(max_length=64)),
                ('shopadd1', models.CharField(max_length=100)),
                ('shopadd2', models.CharField(max_length=100)),
                ('latitude', models.TextField()),
                ('longitude', models.TextField()),
                ('contactno', models.IntegerField()),
                ('altcontact', models.CharField(max_length=12)),
                ('website', models.CharField(max_length=64)),
                ('opentime', models.TimeField()),
                ('closetime', models.TimeField()),
                ('describe', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='aravalli.create_shop')),
            ],
        ),
    ]
